### ISSUE TITLE
[SR-127] Metatype is not working with generics and is operator if used with protocol

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#42749]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-127      |
   |Radar             | None         |
   |Original Reporter | TomasLinhart (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 98664401251c2586e01d3087356d5096

  </details>

**Issue Description:**

If you retrieve a metatype directly without using a generics and you use operator `is`, it works correctly for both class and protocol. If you do same but you put generics between, it doesn't work anymore for protocol, it keeps working only for class.

It would be nice if there was a way where it is possible to check for `T` if `Any.Type` is `T.Type`.

``` java
protocol MyProtocol {}
class MyClass: MyProtocol {}

func checkConformanceFor<T>(obj: Any.Type, type: T.Type) -> Bool {
    return obj is T.Type
}

print(checkConformanceFor(MyClass.self, type: MyClass.self)) // This works
print(checkConformanceFor(MyClass.self, type: MyProtocol.self)) // This fails

// This is basically same thing and it works correctly.
print(MyClass.self is MyClass.Type)
print(MyClass.self is MyProtocol.Type)
```

**Comment by AnthonyLatsis** [comment]
We need a way to spell the instance of an existential metatype to make this possible. The new existential metatype spelling is `any P.Type`, so the first thing that comes to mind is `any P.self`.

@hborla has this been brought up before?

**Comment by hborla** [comment]
@AnthonyLatsis It doesn't make sense to have an instance of an existential metatype using `P.self` because this doesn't actually provide a concrete metatype whose instance conforms to `P`. For example, you wouldn't be able to call any static methods from `P` on an instance of `P.self`, so this isn't really an instance of an existential metatype.

What I think you're getting at is the ability to generalize over protocol constraints, e.g. introduce a "protocol constraint parameter" that can be substituted with protocol constraints, e.g. `P.self` (without `any`). This idea did come up during the SE-0335 discussions on the forums, but I don't believe anybody has pursed it further!

**Comment by AnthonyLatsis** [comment]
Oh, right, this would defeat the concept of an existential metatype, because an instance of `any P.Type` may then happen to be abstract.

> What I think you're getting at is the ability to generalize over protocol constraints

Yeah, I remember myself and other people rehashing similar ideas on the forums over the years. The original call was to enable constraining a generic parameter to a certain class of types, like enums or existentials. `: class` was still a thing back then, so `: protocol` felt like a natural extension of the now-deprecated syntax.

**Comment by AnthonyLatsis** [comment]
So, as Holly mentions, we could discuss something more idiomatic as in
```swift
func conforms<T, protocol Proto>(type: T.Type, to: (any Proto).Type) -> Bool {
  return T.self is any Proto.Type
}

protocol P {}
struct S: P {}

conforms(S.self, (any P).self) // true
```

in a future proposal. But today, you can implement and use a generic conformance check like this:

```swift
func conforms<T, ExistMeta>(type: T.Type, to: ExistMeta.Type) -> Bool {
  return T.self is ExistMeta
}

protocol P {}
struct S: P {}

conforms(type: S.self, to: (any P.Type).self) // true
```

The behavior shown in the original example is correct because the function call binds `T` to `any P`, and `T.Type` is `(any P).Type`, the singleton metatype.
