### ISSUE TITLE
[SR-565] only require full enum name once in closures

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift#43182]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-565      |
   |Radar             | None         |
   |Original Reporter | revanistT3 (JIRA User)      |
   |Type              | Improvement    |

<details>
  <summary>Environment</summary>

ubuntu 15.10

Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 54dcd16759)  
Target: x86_64-unknown-linux-gnu

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Improvement, LanguageFeatureRequest        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 19c6599b83d0cdb717c14d434b92c64b

  </details>

**Issue Description:**

enum e {case One,Two}  
let b = {e.One; e.Two}  
\_\_\_\_\_\_\_\_\_\_\_\_^ second "e" is redundant

p.s. yes, I know that code is useless, but if statements don’t work in closures. Already reported that

**Comment by AnthonyLatsis** [comment]
I am going to close for the following reasons:

* The examples are contrived.
* Being able to write `{ -> Enum in ($0 == 1) ? .a : .b }` instead of `{ ($0 == 1) ? Enum.a : .b }` by itself does not sound like a motivation that holds its weight.
* The only hypothetical case where I would find this helpful is when
  * you would rather specify an explicit upper bound for the result type to disambiguate, and
  * you reasonably prefer to use anonymous arguments.

If anyone wants to revisit this later—you are welcome to reopen.
