### ISSUE TITLE
Compiler should emit warning on use of final keyword with actors

### ISSUE THREAD

**Issue by sarahnicoleboo** [swiftlang/swift#74200]
### Description

swiftc allows the use of the final keyword with actors even though the language does not currently supports inheritance with actors.

### Reproduction

```swift
final actor Actor {}
```

### Expected behavior

Compiler warning emitted explaining that the final keyword is unnecessary as inheritance with actors is not currently supported.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by hborla** [comment]
I disagree that this is a bug. `final` is unnecessary, but the compiler typically doesn't warn about things that are unnecessary. It isn't _wrong_; actors today are always final.

**Comment by AnthonyLatsis** [comment]
I can see how the `final` keyword` might trick someone that is new to actors into thinking that inheritance is supported. But because actor inheritance is a possible future direction, an author’s decision to make the `final` explicit in specific cases — as well as our decision to not complain about this — can be seen as prudent.
