### ISSUE TITLE
[stdlib] Should the `RangeSet` types be `@frozen`?

### ISSUE THREAD

**Issue by benrimmington** [swiftlang/swift#75851]
Should the following types from [SE-0270][] be `@frozen` in Swift 6?

* [`RangeSet`](https://github.com/swiftlang/swift/blob/main/stdlib/public/core/RangeSet.swift)
* [`RangeSet.Ranges`](https://github.com/swiftlang/swift/blob/main/stdlib/public/core/RangeSetRanges.swift)
* [`DiscontiguousSlice`](https://github.com/swiftlang/swift/blob/main/stdlib/public/core/DiscontiguousSlice.swift)
* [`DiscontiguousSlice.Index`](https://github.com/swiftlang/swift/blob/main/stdlib/public/core/DiscontiguousSlice.swift)

Cc: @swiftlang/standard-librarians

[SE-0270]: <https://github.com/swiftlang/swift-evolution/blob/main/proposals/0270-rangeset-and-collection-operations.md>

**Comment by jmschonfeld** [comment]
When we landed those types in the stdlib, we decided against making `RangeSet.Ranges` `@frozen` so that we'd have flexibility in the future to update the underlying storage of the `RangeSet` type (for example to special case certain sets like the empty or single element sets, or to use a tree-like structure rather than a flat array). IIRC, when testing performance of `RangeSet` I determined that marking the surrounding types as `@frozen` had insignificant performance impact because the underlying storage type was still non-frozen, and would make it easier to adapt to new storage within `RangeSet.Ranges` by leaving them unfrozen. Making these all `@frozen` certainly would help with performance, but in the end if I'm remembering correctly we determined that for this type the flexibility was the better choice.

**Comment by benrimmington** [comment]
@jmschonfeld Thanks for the detailed explanation. I should have read the [final review][] of your pull request:

> The big caveat is that this is an opaque Collection type, a big deviation from most previous stdlib additions.

[final review]: <https://github.com/swiftlang/swift/pull/69766#pullrequestreview-1809924963>
