### ISSUE TITLE
'Int?' is default initializable, but 'Optional<Int>' is not

### ISSUE THREAD

**Issue by Sweeper777** [swiftlang/swift#77426]
### Description

A class with an uninitialised property of type `Int?` has a synthesised initialiser, but if the type were changed to `Optional<Int>`, it does not compile without explicitly writing initialiser.

### Reproduction

```swift
class C { // Class 'C' has no initializers
    var p: Optional<Int>
}
```

### Expected behavior

The code should compile without errors, because it is semantically the same as

```swift
class C {
    var p: Int?
}
```

### Environment

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0

### Additional information

In commit 25e4ca9, the following was added to `isDefaultInitializable` in Decl.cpp:

```cpp
  // Also support the desugared 'Optional<T>' spelling.
  if (!ctx.isSwiftVersionAtLeast(5)) {
    if (auto *identRepr = dyn_cast<SimpleIdentTypeRepr>(typeRepr)) {
      if (identRepr->getIdentifier() == ctx.Id_Void)
        return true;
    }
    if (auto *identRepr = dyn_cast<GenericIdentTypeRepr>(typeRepr)) {
      if (identRepr->getIdentifier() == ctx.Id_Optional &&
          identRepr->getNumGenericArgs() == 1)
        return true;
    }
  }
```

It is very weird that `Optional<Int>` is default initializable only when `!ctx.isSwiftVersionAtLeast(5)`. Perhaps the `!` should be removed?

Credits to [matt's Stack Overflow question](https://stackoverflow.com/q/79163751/5133585) for discovering this.

**Comment by hamishknight** [comment]
Duplicate of #53322

As I understand it, the logic checking for `Optional<T>` there is compatibility logic since it sounds like we may have previously allowed default initialization for types with that spelling prior to Swift 5. If we wanted to properly support this behavior though, this wouldn't really be the right way to do it, as it wouldn't support things like typealiases and e.g the following shouldn't be considered default initializable:

```swift
struct Optional<T> {}
class C {
  var x: Optional<Int>
}
```

The right way to do this would be to first resolve the TypeRepr, and then check if the resulting type is optional.
